### ISSUE TITLE
12.0.4 - This app cannot be enabled because it makes the server unstable.

### ISSUE THREAD

**Issue by sunjam** [soudis/discoursesso#2]
![unstable-error](https://user-images.githubusercontent.com/1787238/33645559-58e08136-da00-11e7-8fb3-b243d06c0d5a.png)

Refuses to install from the App Store.

**Comment by moretocome** [comment]
Same issue, same version. I see this in the log:
```
Exception: Cannot include autoload. Did you run install dependencies using composer?
```
Debian stretch, php7.0 and Apache2 from repos.

**Comment by soudis** [comment]
Sorry guys, seems that i checked in the thing without the libraries. As a workaround you can install it manually in the apps directory and then run "composer install" or "make" within the plugin directory. I'll fix it within the next weeks

**Comment by moretocome** [comment]
Thank you for the reply. Unfortunately it seems I need php7.1 which is not available in the Stretch repos.
```
make composer
make[1]: Entering directory '/var/www/nextcloud/apps/discoursesso'
No composer command available, downloading a copy from the web
mkdir -p /var/www/nextcloud/apps/discoursesso/build/tools
curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
Downloading...

Composer (version 1.5.6) successfully installed to: /var/www/nextcloud/apps/discoursesso/composer.phar
Use it: php composer.phar

mv composer.phar /var/www/nextcloud/apps/discoursesso/build/tools
php /var/www/nextcloud/apps/discoursesso/build/tools/composer.phar install --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 3.4.4 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpunit/phpunit-mock-objects 3.4.4 -> satisfiable by phpunit/phpunit-mock-objects[3.4.4].

Makefile:73: recipe for target 'composer' failed
make[1]: *** [composer] Error 2
make[1]: Leaving directory '/var/www/nextcloud/apps/discoursesso'
Makefile:59: recipe for target 'build' failed
make: *** [build] Error 2
```
Merry Christmas :)

**Comment by y0va** [comment]
Probably same issue when trying to update from 12.0.3 to 12.0.4:

```
% docker-compose exec --user www-data app php occ upgrade    
An unhandled exception has been thrown:
Exception: Cannot include autoload. Did you run install dependencies using composer? in /var/www/html/apps/discoursesso/appinfo/app.php:7
Stack trace:
#0 /var/www/html/lib/private/legacy/app.php(209): require_once()
#1 /var/www/html/lib/private/legacy/app.php(149): OC_App::requireAppFile('discoursesso')
#2 /var/www/html/lib/private/legacy/app.php(124): OC_App::loadApp('discoursesso')
#3 /var/www/html/lib/private/Console/Application.php(104): OC_App::loadApps()
#4 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/occ(11): require_once('/var/www/html/c...')
#6 {main}%       
```

**Comment by almereyda** [comment]
@y0va yes, you need to run something like

    composer install

within the container where the plugin is installed. @soudis mentioned this above. If this is a (host-mounted) Docker volume, changes will be persisted for subsequent container recreations.

**Comment by soudis** [comment]
Hi there, sorry for the long delay, but with NC 13 i updated the app to work out of the box. You should be able to install it right from the app store.
